### PR TITLE
Improve readability

### PR DESCRIPTION
**Pull request by DaniPopes**
A bunch of minor changes, tried to split into as many commits as possible for easier reviewing

References:
- rust docs: <https://doc.rust-lang.org/stable/std/ops/>
- ethers bn examples: <https://github.com/gakonst/ethers-rs/tree/master/examples/big-numbers/examples>

### CODE REVIEW

**Comment by 0xKitsune** [comment]
Hey thanks for the PR, all of your changes look great! 

There were some more recent changes on the development branch that are soon to be merged to main so I changed the merge target to the dev branch. Would you be able to resolve the merge conflicts? Once its all good to go, Ill get everything merged into main.

**Comment by 0xKitsune** [comment]
Quick update, Ill be afk for a bit but if I will fix the merge conflicts later today unless you get to it before me. Thanks again for the PR!

**Comment by DaniPopes** [comment]
@0xKitsune thanks for fixing the merge issues!

That was my mistake, I didn't realize there was a development branch.

The main point of this PR was to use the [operator expressions](https://doc.rust-lang.org/reference/expressions/operator-expr.html#negation-operators) instead of the more verbose `std::ops` trait  methods. While I understand that the latter is easier to integrate with Yul low-level operations, it still makes it overly-verbose and complicated to read from the outside, and it does not provide any extra performance whatsoever.

Also, since we're using `ruint` for the internal uint operations, we can simply use the normal operators for `overflowing_*().0` or `wrapping_*()` operations: <https://docs.rs/ruint/latest/ruint/struct.Uint.html#notable-differences-from-std-uint-types>

> The operators +, -, *, etc. using wrapping math by default.

I can open another PR for this if you want.

**Comment by 0xKitsune** [comment]
> Also, since we're using ruint for the internal uint operations, we can simply use the normal operators for overflowing_*().0 or wrapping_*() operations: https://docs.rs/ruint/latest/ruint/struct.Uint.html#notable-differences-from-std-uint-types

Awesome, I didn't notice this at first. Feel free to make another PR and thanks for the help!

**Pull request merged**
